"""Added cronometer model and daily log mixin

Revision ID: 4dfcafa29296
Revises: 04ffad29c5a6
Create Date: 2020-08-03 16:33:29.852671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfcafa29296'
down_revision = '04ffad29c5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_fat_percentage',
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('app_user_id', 'date')
    )
    op.create_table('cronometer_exercise',
    sa.Column('exercise', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('mintues', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('exercise', 'app_user_id', 'date_time')
    )
    op.drop_column('weigh_in', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weigh_in', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_table('cronometer_exercise')
    op.drop_table('body_fat_percentage')
    # ### end Alembic commands ###
