"""Added loseit export table

Revision ID: c24cec7b7502
Revises: 
Create Date: 2020-06-16 19:46:34.327109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24cec7b7502'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loseit_food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_date', sa.Date(), nullable=True),
    sa.Column('raw_name', sa.String(), nullable=True),
    sa.Column('raw_type', sa.String(), nullable=True),
    sa.Column('raw_quantity', sa.Float(), nullable=True),
    sa.Column('raw_units', sa.String(), nullable=True),
    sa.Column('raw_calories', sa.Integer(), nullable=True),
    sa.Column('raw_fat_g', sa.Float(), nullable=True),
    sa.Column('raw_protein_g', sa.Float(), nullable=True),
    sa.Column('raw_carbohydrates_g', sa.Float(), nullable=True),
    sa.Column('raw_saturated_fat_g', sa.Float(), nullable=True),
    sa.Column('raw_sugars_g', sa.Float(), nullable=True),
    sa.Column('raw_fiber_g', sa.Float(), nullable=True),
    sa.Column('raw_cholesterol_mg', sa.Float(), nullable=True),
    sa.Column('raw_sodium_mg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loseit_food')
    # ### end Alembic commands ###
