"""mood_table_type_change

Revision ID: 04ffad29c5a6
Revises: 9920ce25864a
Create Date: 2020-07-14 19:11:28.067330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ffad29c5a6'
down_revision = '9920ce25864a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mood_survey_response', 'sleep_hours',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mood_survey_response', 'sleep_hours',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
