"""empty message

Revision ID: 7a45e05f3840
Revises: f9486242a7ec
Create Date: 2020-08-21 14:20:39.192690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a45e05f3840'
down_revision = 'f9486242a7ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.alter_column(
        'cronometer_exercise',
        'mintues',
        new_column_name='minutes',
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.alter_column(
        'cronometer_exercise',
        'minutes',
        new_column_name='mintues',
    )
