"""remove username use email

Revision ID: 9e68a6add6fb
Revises: 47cd412fe9ed
Create Date: 2020-08-17 14:07:38.576474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e68a6add6fb'
down_revision = '47cd412fe9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'app_user', ['email'])
    op.drop_column('app_user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'app_user', type_='unique')
    # ### end Alembic commands ###
