"""empty message

Revision ID: ba61a3eb7d95
Revises: 7a45e05f3840
Create Date: 2020-08-21 15:05:54.803576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba61a3eb7d95'
down_revision = '7a45e05f3840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.alter_column(
        'cronometer_biometric',
        'Ammount',
        nullable=True,
        new_column_name='amount',
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.alter_column(
        'cronometer_biometric',
        'amount',
        nullable=True,
        new_column_name='Ammount',
    )
