"""made user fks not nullable

Revision ID: f8a57af83ce9
Revises: d65de20d5127
Create Date: 2020-07-08 16:10:23.323625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a57af83ce9'
down_revision = 'd65de20d5127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loseit_food', 'app_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mood_survey_response', 'app_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('weigh_in', 'app_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weigh_in', 'app_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mood_survey_response', 'app_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('loseit_food', 'app_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
