"""Added user table and fixed column spelling

Revision ID: 6d893fd532d7
Revises: 2d4434fa7f2b
Create Date: 2020-07-08 14:34:33.897929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d893fd532d7'
down_revision = '2d4434fa7f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mood_survey_response', sa.Column('app_user_id', sa.Integer(), nullable=True))
    op.add_column('mood_survey_response', sa.Column('date_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'mood_survey_response', 'app_user', ['app_user_id'], ['id'])
    op.add_column('weigh_in', sa.Column('app_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'weigh_in', 'app_user', ['app_user_id'], ['id'])
    # ### end Alembic commands ###
    op.alter_column(
        'mood_survey_response',
        'adderal_crash',
        new_column_name='adderall_crash',
    )


def downgrade():
    pass
