"""Added weight log table

Revision ID: 895bb4c6e637
Revises: c24cec7b7502
Create Date: 2020-06-17 16:20:02.610351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895bb4c6e637'
down_revision = 'c24cec7b7502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weigh_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weigh_in')
    # ### end Alembic commands ###
