"""sleep and mood table updates

Revision ID: 9920ce25864a
Revises: beef3334794f
Create Date: 2020-07-14 18:59:21.423434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9920ce25864a'
down_revision = 'beef3334794f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_survey_response',
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('rise_ease', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('app_user_id', 'date_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleep_survey_response')
    # ### end Alembic commands ###
