"""added unique constraint to mood_survey

Revision ID: bf3a905413ee
Revises: f8a57af83ce9
Create Date: 2020-07-08 16:51:55.454944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3a905413ee'
down_revision = 'f8a57af83ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mood_survey_response', ['app_user_id', 'date_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mood_survey_response', type_='unique')
    # ### end Alembic commands ###
